package com.bth.gui.csvchooser;

import com.bth.io.output.ExamOutput;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class CsvDirectoryChoice {

  public JFileChooser fileChooser1;
  public JPanel primaryPanel;

  public CsvDirectoryChoice() {
    init();
  }

  public void init() {

    fileChooser1.setVisible(true);
    fileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    fileChooser1.setDialogTitle("In which directory should CSV be outputted?");

    int returnVal = fileChooser1.showSaveDialog(primaryPanel);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      if (fileChooser1.getSelectedFile().isDirectory()) {
        ExamOutput.setDirectory(fileChooser1.getSelectedFile().getAbsolutePath());
      } else {
        JOptionPane.showMessageDialog(null, "Incorrect input.");
      }
    }
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    primaryPanel = new JPanel();
    primaryPanel.setLayout(new GridLayoutManager(1, 2, new Insets(5, 5, 5, 5), -1, -1));
    primaryPanel.setInheritsPopupMenu(false);
    primaryPanel.setMaximumSize(new Dimension(650, 600));
    primaryPanel.setMinimumSize(new Dimension(650, 600));
    primaryPanel.setPreferredSize(new Dimension(650, 600));
    fileChooser1 = new JFileChooser();
    fileChooser1.setAcceptAllFileFilterUsed(true);
    fileChooser1.setDoubleBuffered(true);
    primaryPanel.add(fileChooser1,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
            null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return primaryPanel;
  }
}
